# 넘파이 numpy 강의노트 실습

In [71]:
import numpy as np

In [72]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[2,3,4]])

In [73]:
array1

array([1, 2, 3])

In [74]:
array2
## ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
## 즉, 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없음

array([[1, 2, 3],
       [2, 3, 4]])

## ndarray를 편리하게 생성하기
### arange, zeros,ones

특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화 생성해야 할 경우
arange(), zeros(), ones()를 이용해 쉽게 ndarray를 생성할 수 있다.    

*주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야할 경우에 사용*

In [13]:
np.arange(10)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [15]:
np.zeros((3,2), dtype='int32')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## ndarray의 차원크기를 변경하는 reshape()
reshape()는 ndarray를 특정 차원 및 형태로 변환한다.  
변환 형태를 함수 인자로 부여한다.

In [23]:
array1d = np.array([1,2,3,4])
array1d.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])

In [41]:
a=[0,1,2,3]
b=np.reshape(a,(2,2))
print(b)

[[0 1]
 [2 3]]


## 단일 값 추출 - 1차원 ndarrary
ndarrary는 axis를 기준으로 0부터 시작하는 위치 인덱스 값을 가지고 있음.  
해당 인덱스 값을 []에 명시하여 단일 값을 추출함.  
마이너스가 인덱스로 사용되면 맨 뒤에서부터 위치를 지정함.

In [25]:
array1d[3]

4

In [27]:
array1d[-3]

2

## 단일 값 추출 - 2차원 ndarrary

In [43]:
b[0,1]

1

## Slicing슬라이싱
슬라이싱은 :을 이용하여 연속된 값을 선택한다

In [44]:
# 1차원 ndarray
array1[1:]

array([2, 3])

In [46]:
# 2차원 ndarray
b[0:1,:]

array([[0, 1]])

## 팬시 인덱싱
팬시 인덱싱 (fancy indexing)은 리스트나 ndarray로 인덱스 집합을 지정하면  
해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱스 방식

In [51]:
c=np.array([0,1,2,3,4,5,6,7,8])
index=np.array([1,4,5])
print(c[index])

[1 4 5]


In [52]:
b=np.array([[0,1,2],[3,4,5],[6,7,8]])
index=np.array([0,2])
index2=np.array([1,2])
print(b[index,index2])

[1 8]


## 불린 인덱싱
불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식이다.  
step1 : 조건을 [] 내에 입력한다  
step2 : false 값은 무시하고 true 값에 해당하는 index 값만 저장한다  
step3 : 저장된 index 값으로 데이터를 조회한다

In [60]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
bool_indexing=(a>5)
print(bool_indexing)
index = np.array([True, False, False, True, False, True, True, True, False])
print(a[index])

[False False False False False False  True  True  True]
[0 3 5 6 7]


## 배열의 정렬 - sort()와 argsort()
**넘파이 sort()유형**  
- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환  
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 none  
  
    
*np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬.  
내림차순으로 정렬하기 위해서는 [::-1] 을 적용한다.  
np.sort[::-1] 과 같이 사용하면 된다.*  
  
    
argsort()  
원본 행렬 정렬 시 정렬된 행렬의 원래 인덱스를 필요로 할 때 np.argsort()를 이용함.  
np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환함.

In [61]:
np.sort(b,axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
np.sort(b,axis=0)[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 선형대수 연산 - 행렬 내적, 전치 행렬

In [69]:
x = np.array([5,10])
w = np.array([[1,3,5],[2,4,6]])
print(w)
 
w.shape
y = np.dot(x,w)
print(y)

# 출처: https://www.crocus.co.kr/1505 [Crocus]

[[1 3 5]
 [2 4 6]]
[25 55 85]


In [70]:
np.transpose(b)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])