# Numpy 기초 연습문제

In [2]:
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [5]:
a = np.zeros((3, 4)) #3행 4열 형태로 ndarray 생성
a

# arage(), zeros(), ones()란?
# 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화 생성해야할 경우 사용
# 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야할 경우에 사용함



##### ndarray에 대한 일반적인 설명#####
# ndarray : N 차원(Dimension) 배열(Array) 객체
# ndarray는 numpy 모듈의 array()함수로 생성
# np.array([1,2,3],[2,3,4]) -> 이 경우 2차원 배열이 생성된 것

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [6]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [7]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [8]:
a[1,2] #2열 3행에 있는 것을 꺼내기 위해서 1,2 (인덱스는 0부터 시작)

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [9]:
a.shape #데이터프레임 a의 형태 확인 (3행 4열)

(3, 4)

In [10]:
a[[1], :] 
# :은 슬라이싱으로 연속된 값을 선택한다.
# 즉, 2행의 연속 값인 5,6,7,8이 인덱싱

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [11]:
a[:,[1, 2]] #행은 연속값으로 나오되 둘째 열과 셋째 열이 나오려면 1,2 로 인덱싱한다.

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불린 인덱싱을 하시오.

In [12]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [14]:
a[a <= 6]
# 조건 필터링과 검색을 동시에 할 수 있는 인덱싱 방법
# a ndarray 내에서 6보다 작거나 같은 값을 가진 ndarray 추출

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [11]:
b = np.random.random((3, 4))
b

array([[0.95141953, 0.72171683, 0.17406397, 0.31400552],
       [0.85747982, 0.16034805, 0.77565377, 0.9022088 ],
       [0.97850532, 0.34055279, 0.76916852, 0.42811541]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [12]:
c = a * b
c

array([[0.95141953, 1.44343365, 0.5221919 , 1.25602206],
       [4.28739911, 0.96208828, 5.42957642, 7.21767037],
       [8.80654791, 3.40552787, 8.46085377, 5.13738488]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [13]:
d = b.T # transpose로도 계산 가능
d

array([[0.95141953, 0.85747982, 0.97850532],
       [0.72171683, 0.16034805, 0.34055279],
       [0.17406397, 0.77565377, 0.76916852],
       [0.31400552, 0.9022088 , 0.42811541]])

In [14]:
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [15]:
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [16]:
e = a.dot(d)
e
# a의 1행의 각 값 * d의 1열의 각 값을 곱해 e의 1행 1열에 위치
# a의 1행의 각 값 * d의 2열의 각 값을 곱해 e의 1행 2열에 위치
# a의 1행의 각 값 * d의 3열의 각 값을 곱해 e의 1행 3열에 위치
# a의 2행의 각 값 * d의 1열의 각 값을 곱해 e의 2행 1열에 위치
# a의 2행의 각 값 * d의 2열의 각 값을 곱해 e의 2행 2열에 위치
# 위와 같은 방식으로 계산되는 행렬곱을 np.dot(A,B)로 간단하게 가능하게 한다

array([[ 4.17306714,  7.11397243,  5.6795781 ],
       [12.81789049, 17.89673419, 15.74494627],
       [21.46271384, 28.67949595, 25.81031444]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [17]:
np.sum(e, axis=1)

array([16.96661767, 46.45957095, 75.95252423])